"""Write the teaching review a student sees when a PairPath session ends.

It used to be the exercise's fixed yes/no prompts - the same five questions for
every pair that ever attempted it, whether they solved it in two minutes or
never ran the code. This writes a short review about the session that actually
happened: the student's own final code, whether it worked, and - for a pair -
how the two of them worked together. It teaches a little, then asks a little,
one step at a time.

Generated by the same model and the same syllabus notes as the lessons.

PairPath calls this from its server (app/api/session_review.py), stores the
result once per session so both partners get the same review, and keeps the
answers to itself until each one is given. Nothing here stores anything.

Everything the model returns is checked before it is used. A step whose
question has two correct options, or an answer index pointing past the end of
the options, would score a student wrong for a right answer - so a response
that does not hold together is regenerated once and then refused, never
patched into shape.
"""

from __future__ import annotations

import json
from typing import Literal, Optional

from pydantic import BaseModel, Field

from app.core.config import settings
from app.services.llm import LLMUnavailable, generate, strip_code_fence
from app.services.rag_service import FOUND, UNAVAILABLE, retrieve_notes


# ── What PairPath sends ──────────────────────────────────────────────────────


class ExerciseInfo(BaseModel):
    title: str = Field(max_length=300)
    description: str = Field(max_length=6000)
    difficulty: Optional[str] = Field(default=None, max_length=40)
    concept_tags: list[str] = Field(default_factory=list, max_length=20)
    # What a correct program prints, when the exercise has one answer.
    expected_output: Optional[str] = Field(default=None, max_length=4000)
    # For the model only. The student sees it after the review, from PairPath.
    reference_solution: str = Field(max_length=20000)


class RunSummary(BaseModel):
    total: int = Field(ge=0, le=10000)
    # Printed the expected output.
    correct: int = Field(ge=0, le=10000)
    # Did not compile, or threw.
    failed: int = Field(ge=0, le=10000)


class Teamwork(BaseModel):
    """How a pair worked, from the session's recorded events. Counts only.

    No chat text and no names: what the students wrote to each other is not
    sent to the model, and the review is shared by both partners, so "you" has
    to mean either of them.
    """

    duration_minutes: int = Field(ge=0, le=100000)
    role_switches: int = Field(ge=0, le=10000)
    edits_by_driver: int = Field(ge=0, le=1000000)
    edits_by_navigator: int = Field(ge=0, le=1000000)
    runs_by_driver: int = Field(ge=0, le=10000)
    runs_by_navigator: int = Field(ge=0, le=10000)
    chat_messages: int = Field(ge=0, le=100000)
    # The larger of the two partners' shares of all edits, 50-100.
    busiest_partner_edit_percent: int = Field(ge=0, le=100)


class SessionReviewRequest(BaseModel):
    mode: Literal["solo", "pair"]
    exercise: ExerciseInfo
    code: str = Field(max_length=20000)
    # solved: a run printed the expected output. unsolved: graded runs, none
    # right. ungraded: nothing to compare against, or never run.
    outcome: Literal["solved", "unsolved", "ungraded"]
    runs: RunSummary
    teamwork: Optional[Teamwork] = None


# ── What it returns ──────────────────────────────────────────────────────────

MIN_STEPS, MAX_STEPS = 3, 4
MIN_OPTIONS, MAX_OPTIONS = 3, 4
MAX_REFLECTIONS = 2


class ReviewError(LLMUnavailable):
    """The model answered, but not with a review that holds together."""


PROMPT = """
You are 'Code Guru', a friendly Java tutor for first-year university students.

{who} just finished a practice exercise. Write a short TEACHING REVIEW of
this session: teach a little, then ask a little, one step at a time. It is about
THIS exercise and THIS code - not a general lesson on the topic.

=== THE EXERCISE ===
Title: {title}
Task: {description}
Difficulty: {difficulty}
Concepts: {concepts}
{expected}

=== THEIR FINAL CODE (line numbers are added here and are not part of the code) ===
{numbered_code}

=== A MODEL SOLUTION - FOR YOU ONLY ===
The student sees this only after the review is finished. Use it to understand
the right approach. Never paste it, or any complete corrected program, into
the review.
{solution}

=== WHAT HAPPENED ===
{outcome}
{runs}
{teamwork}

=== SYLLABUS NOTES (background only) ===
{notes}

=== WRITE THE REVIEW ===
- {step_range} steps. Each step has:
  - "teach": 2-3 short, plain sentences explaining ONE idea about their code.
  - "lines": [first, last], the lines of THEIR code the step is about, using the
    numbering above, or null when the step is not about particular lines.
  - "question": one multiple-choice question that checks the idea just taught.
    Ask what the code does, why, what it prints, or which change fixes it.
    It must be answerable from their code and the teaching above it.
    {option_range} options, exactly one correct. Wrong options are mistakes a
    beginner really makes, not jokes. Put the correct option in different
    positions across the steps.
    "answer" is the 0-based index of the correct option.
    "explanation": 1-2 sentences on why it is right, and what the most
    tempting wrong option gets wrong.
- {outcome_instruction}
- Speak to the student as "you"{pair_voice}. Never invent names.
- Write code, identifiers and expressions in `backticks`.
{reflection_instruction}
- "title": 3 to 7 words. "summary": 1-2 warm, honest sentences recapping the
  session; if it was not solved, say so kindly.
- "solutionNote": 1-2 sentences shown beside the model solution after the
  review, saying what it does that their code does not - or, if they solved
  it, how the two compare.

Respond ONLY with valid JSON in exactly this shape:
{{
  "title": "...",
  "summary": "...",
  "steps": [
    {{
      "teach": "...",
      "lines": [3, 5],
      "question": {{
        "prompt": "...",
        "options": ["...", "...", "..."],
        "answer": 1,
        "explanation": "..."
      }}
    }}
  ],
  "reflection": [{reflection_shape}],
  "solutionNote": "..."
}}
"""

OUTCOME_TEXT = {
    "solved": "SOLVED: a run printed exactly the expected output.",
    "unsolved": "NOT SOLVED: they ran it, but no run printed the expected output.",
    "ungraded": "NOT GRADED: there was no expected output to compare against, or the code was never run.",
}

OUTCOME_INSTRUCTION = {
    "solved": (
        "It was SOLVED: reinforce WHY their code works, and use one step on a "
        "mistake that would have broken it or a way it could be clearer."
    ),
    "unsolved": (
        "It was NOT SOLVED: the steps must walk them toward the fix - first "
        "where their code goes wrong, then why, then what change fixes it - "
        "so that by the last step they could fix it themselves. Do not hand "
        "them the corrected program."
    ),
    "ungraded": (
        "It was not graded: teach from what their code does compared with what "
        "the task asks, and point them at anything still missing."
    ),
}


def numbered(code: str) -> str:
    lines = code.splitlines() or [""]
    width = len(str(len(lines)))
    return "\n".join(f"{index:>{width}} | {line}" for index, line in enumerate(lines, start=1))


def _teamwork_text(request: SessionReviewRequest) -> str:
    team = request.teamwork
    if request.mode != "pair" or team is None:
        return "They worked ALONE."
    return "\n".join(
        [
            "They worked as a PAIR: one DRIVER types, one NAVIGATOR reviews and guides, and they can swap.",
            f"- Session length: about {team.duration_minutes} minute(s); role switches: {team.role_switches}.",
            f"- Edits while driving: {team.edits_by_driver}; edits while navigating: {team.edits_by_navigator}.",
            f"- One partner made {team.busiest_partner_edit_percent}% of all edits.",
            f"- Runs by the driver: {team.runs_by_driver}; by the navigator: {team.runs_by_navigator}.",
            f"- Chat messages between them: {team.chat_messages}.",
        ]
    )


def _notes_text(request: SessionReviewRequest) -> str:
    tags = request.exercise.concept_tags
    notes = retrieve_notes(
        f"{request.exercise.title} {' '.join(tags)}",
        concept=tags[0] if tags else None,
        k=2,
    )
    if notes.status == FOUND:
        return notes.text
    if notes.status == UNAVAILABLE:
        return "None could be retrieved. Explain from general Java knowledge; do not mention course notes."
    return "None on this topic. Explain from general Java knowledge; do not claim to quote course material."


def build_prompt(request: SessionReviewRequest, notes: str) -> str:
    pair = request.mode == "pair"
    exercise = request.exercise
    return PROMPT.format(
        who="A pair of students" if pair else "A student working alone",
        title=exercise.title,
        description=exercise.description,
        difficulty=exercise.difficulty or "not stated",
        concepts=", ".join(exercise.concept_tags) or "not stated",
        expected=(
            f"Expected output (what a correct program prints):\n{exercise.expected_output}"
            if exercise.expected_output
            else "This exercise has no single expected output."
        ),
        numbered_code=numbered(request.code) if request.code.strip() else "(they left the editor empty)",
        solution=exercise.reference_solution,
        outcome=OUTCOME_TEXT[request.outcome],
        runs=(
            f"Runs: {request.runs.total} in total; {request.runs.correct} printed the expected output; "
            f"{request.runs.failed} failed to compile or crashed."
        ),
        teamwork=_teamwork_text(request),
        notes=notes,
        step_range=f"{MIN_STEPS} or {MAX_STEPS}",
        option_range=f"{MIN_OPTIONS} or {MAX_OPTIONS}",
        outcome_instruction=OUTCOME_INSTRUCTION[request.outcome],
        pair_voice=(
            ", meaning either partner - both read the same review - and \"you and your partner\" for the two of them"
            if pair
            else ""
        ),
        reflection_instruction=(
            "- \"reflection\": 1 or 2 questions about HOW THEY WORKED TOGETHER, built on the\n"
            "  facts under WHAT HAPPENED (role switches, who typed, who ran it, talking).\n"
            "  Each has 3 or 4 options and NO right answer - they are for reflecting, and\n"
            "  are not scored. Do not word any option as the good or the bad one."
            if pair
            else "- \"reflection\": always an empty list - they worked alone."
        ),
        reflection_shape='{"prompt": "...", "options": ["...", "...", "..."]}' if pair else "",
    )


# ── Checking what came back ──────────────────────────────────────────────────


def _parse(text: str) -> dict:
    cleaned = strip_code_fence(text)
    try:
        value = json.loads(cleaned)
    except json.JSONDecodeError:
        start, end = cleaned.find("{"), cleaned.rfind("}")
        if start == -1 or end <= start:
            raise ReviewError("The model did not return a JSON object.")
        try:
            value = json.loads(cleaned[start : end + 1])
        except json.JSONDecodeError as error:
            raise ReviewError(f"The model returned malformed JSON: {error}") from error
    if not isinstance(value, dict):
        raise ReviewError("The model returned JSON that is not an object.")
    return value


def _text(value: object, field: str, limit: int) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ReviewError(f"{field} is missing or empty.")
    return value.strip()[:limit]


def _options(value: object, field: str) -> list[str]:
    if not isinstance(value, list):
        raise ReviewError(f"{field} is not a list.")
    options = [_text(option, field, 300) for option in value]
    if not MIN_OPTIONS - 1 <= len(options) <= MAX_OPTIONS + 1:
        raise ReviewError(f"{field} has {len(options)} options.")
    if len({option.casefold() for option in options}) != len(options):
        raise ReviewError(f"{field} repeats an option.")
    return options


def _lines(value: object, line_count: int) -> Optional[list[int]]:
    """A [first, last] range inside the code, or None. Never an error.

    A range the model got slightly wrong costs a highlight, not the review.
    """
    if not isinstance(value, list) or len(value) != 2:
        return None
    if not all(isinstance(n, int) and not isinstance(n, bool) for n in value):
        return None
    first, last = value
    if first > last:
        first, last = last, first
    if first < 1 or first > line_count:
        return None
    return [first, min(last, line_count)]


def validate_review(raw: dict, request: SessionReviewRequest) -> dict:
    line_count = len(request.code.splitlines()) or 1

    steps_raw = raw.get("steps")
    if not isinstance(steps_raw, list) or not MIN_STEPS - 1 <= len(steps_raw) <= MAX_STEPS + 1:
        raise ReviewError("The review needs 2 to 5 steps.")

    steps = []
    for index, step in enumerate(steps_raw, start=1):
        if not isinstance(step, dict) or not isinstance(step.get("question"), dict):
            raise ReviewError(f"Step {index} has no question.")
        question = step["question"]
        options = _options(question.get("options"), f"step {index} options")
        answer = question.get("answer")
        if not isinstance(answer, int) or isinstance(answer, bool) or not 0 <= answer < len(options):
            raise ReviewError(f"Step {index} answer does not point at an option.")
        steps.append(
            {
                "teach": _text(step.get("teach"), f"step {index} teach", 900),
                "lines": _lines(step.get("lines"), line_count),
                "question": {
                    "prompt": _text(question.get("prompt"), f"step {index} prompt", 400),
                    "options": options,
                    "answer": answer,
                    "explanation": _text(question.get("explanation"), f"step {index} explanation", 600),
                },
            }
        )

    reflection = []
    if request.mode == "pair":
        for index, item in enumerate(raw.get("reflection") or [], start=1):
            if not isinstance(item, dict):
                continue
            try:
                reflection.append(
                    {
                        "prompt": _text(item.get("prompt"), f"reflection {index} prompt", 400),
                        "options": _options(item.get("options"), f"reflection {index} options"),
                    }
                )
            except ReviewError:
                # Unscored and optional: a malformed one is dropped, not fatal.
                continue
        reflection = reflection[:MAX_REFLECTIONS]

    return {
        "title": _text(raw.get("title"), "title", 120),
        "summary": _text(raw.get("summary"), "summary", 600),
        "steps": steps,
        "reflection": reflection,
        "solutionNote": _text(raw.get("solutionNote"), "solutionNote", 600),
    }


def generate_session_review(request: SessionReviewRequest) -> dict:
    """A checked review, or raise LLMUnavailable (LLMQuotaExhausted on quota).

    Tried twice: a model occasionally returns a response that parses but does
    not hold together, and a second attempt usually does. A quota or network
    failure is not retried - it will not have cleared a second later.
    """
    prompt = build_prompt(request, _notes_text(request))

    last_error: ReviewError | None = None
    for _ in range(2):
        try:
            review = validate_review(_parse(generate(prompt)), request)
        except ReviewError as error:
            last_error = error
            print(f"Session review did not hold together: {error}")
            continue
        review["model"] = settings.MODEL_NAME
        return review

    raise last_error or ReviewError("The review could not be generated.")
